version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worldwines_backend
    ports:
      - 8080:8080
    # volumes:
    #   - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: worldwines_frontend
    ports:
      - 5000:80  # Expose port 80 for Nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
